//
//  MovieService.swift
//  ProjetoVIPBootcampSantander
//
//  Created by Fernanda Perovano on 22/10/23.
//

import Foundation
import UIKit

struct MovieService {
    
    var movieList: [Movies] = [
        Movies(name: "Um Sonho de Liberdade", photo: UIImage(named: "umSonhoDeLiberdade"), sumary: "Em 1946, Andy Dufresne (Tim Robbins), um jovem e bem sucedido banqueiro, tem a sua vida radicalmente modificada ao ser condenado por um crime que nunca cometeu, o homicídio de sua esposa e do amante dela. Ele é mandado para uma prisão que é o pesadelo de qualquer detento, a Penitenciária Estadual de Shawshank, no Maine. Lá ele irá cumprir a pena perpétua. Andy logo será apresentado a Warden Norton (Bob Gunton), o corrupto e cruel agente penitenciário, que usa a Bíblia como arma de controle e ao Capitão Byron Hadley (Clancy Brown) que trata os internos como animais. Andy faz amizade com Ellis Boyd Redding (Morgan Freeman), um prisioneiro que cumpre pena há 20 anos e controla o mercado negro da instituição."),
        Movies(name: "Titanic", photo: UIImage(named: "titanic"), sumary: "Jack Dawson (Leonardo DiCaprio) é um jovem aventureiro que, na mesa de jogo, ganha uma passagem para a primeira viagem do transatlântico Titanic. Trata-se de um luxuoso e imponente navio, anunciado na época como inafundável, que parte para os Estados Unidos. Nele está também Rose DeWitt Bukater (Kate Winslet), a jovem noiva de Caledon Hockley (Billy Zane). Rose está descontente com sua vida, já que sente-se sufocada pelos costumes da elite e não ama Caledon. Entretanto, ela precisa se casar com ele para manter o bom nome da família, que está falida. Um dia, desesperada, Rose ameaça se atirar do Titanic, mas Jack consegue demovê-la da ideia. Pelo ato ele é convidado a jantar na primeira classe, onde começa a se tornar mais próximo de Rose. Logo eles se apaixonam, despertando a fúria de Caledon. A situação fica ainda mais complicada quando o Titanic se choca com um iceberg, provocando algo que ninguém imaginava ser possível: o naufrágio do navio."),
        Movies(name: "Um Contratempo", photo: UIImage(named: "umContratempo"), sumary: "Tudo está indo muito bem para Adrian Doria (Mario Casas). Seu negócio é um sucesso e lhe trouxe riqueza, sua bela esposa teve a criança perfeita, e sua amante está bem com o caso dos dois escondido. Tudo está ótimo até que Doria desperta num quarto de hotel, depois de ser atingido na cabeça, e encontra sua amante morta no banheiro, coberta com um monte de notas em euros. Pior, o quarto é trancado por dentro e não tem nenhuma maneira de entrar ou sair. Com tudo o que construiu desmoronando aos seus pés, Doria recorre a melhor advogada de defesa da Espanha, Virginia Goodman (Ana Wagener), e eles tentam descobrir o que realmente aconteceu na noite anterior."),
        Movies(name: "Cegos, Surdos e Loucos", photo: UIImage(named: "cegosSurdosELoucos"), sumary: "O dono de uma banca de jornais, Dave Lyons (Gene Wilder), que é surdo, dá um emprego para Wallace Karue (Richard Pryor), que é cego. Perto da banca há um assassinato cometido por Eve (Joan Severance), uma matadora profissional, mas a vítima conseguiu se livrar de uma aparente moeda (na verdade um supercondutor de energia) misturando com outras moedas, que haviam na banca. Wally ouviu um tiro e Dave só viu as pernas de Eve, mas quando a polícia chega os dois são presos como suspeitos. Como Eve e seu cúmplice inglês, Kirgo (Kevin Spacey), não encontram na valise da vítima o material encomendado pelo mandante, Sutherland (Anthony Zerbe), então Eve e Kirgo se passam por advogados que querem libertar os acusados, pois têm certeza que a moeda está com eles. Mas Wally e Dave fogem e são perseguidos, pela polícia e pelos bandidos."),
        Movies(name: "Ghost - Do Outro Lado da Vida", photo: UIImage(named:"ghost"), sumary: "Em Ghost - Do Outro Lado da Vida, Sam Wheat (Patrick Swayze) e Molly Jensen (Demi Moore) formam um casal muito apaixonado que tem suas vidas destruídas, pois ao voltarem de uma apresentação de Hamlet são atacados e Sam é morto. No entanto, seu espírito não vai para o outro plano e decide ajudar Molly, pois ela corre o risco de ser morta e quem comanda a trama, e o mesmo que tirou sua vida, é quem Sam considerava seu melhor amigo. Para poder se comunicar com Molly ele utiliza Oda Mae Brown (Whoopi Goldberg), uma médium trambiqueira que consegue ouvi-lo, para desta maneira alertar sua esposa do perigo que corre."),
        Movies(name: "Harry Potter e a Pedra Filosofal", photo: UIImage(named: "harryPotter"), sumary: "Harry Potter (Daniel Radcliffe) é um garoto órfão de 10 anos que vive infeliz com seus tios, os Dursley. Até que, repentinamente, ele recebe uma carta contendo um convite para ingressar em Hogwarts, uma famosa escola especializada em formar jovens bruxos. Inicialmente Harry é impedido de ler a carta por seu tio Válter (Richard Griffiths), mas logo ele recebe a visita de Hagrid (Robbie Coltrane), o guarda-caça de Hogwarts, que chega em sua casa para levá-lo até a escola. A partir de então Harry passa a conhecer um mundo mágico que jamais imaginara, vivendo as mais diversas aventuras com seus mais novos amigos, Rony Weasley (Rupert Grint) e Hermione Granger (Emma Watson)."),
        Movies(name: "Mudança de Hábito", photo: UIImage(named: "mudancaDeHabito"), sumary: "Em Reno, Nevada, Deloris Van Cartier (Whoopi Goldberg) é uma cantora que acidentalmente testemunha um brutal assassinato cometido pelo seu namorado, Vince LaRocca (Harvey Keitel), um gângster. Enquanto tentam capturar Vince, um detetive, Eddie Souther (Bill Nunn), é encarregado de protegê-la. Deloris é colocada no programa de proteção às testemunhas e é mandada para um convento em São Francisco disfarçada de freira, usando o nome de irmã Mary Clarence. Mas seu jeito extrovertido, que não é aprovado pela Madre Superiora (Maggie Smith), acaba fazendo ela dar uma nova vida ao coral, chamando a atenção das pessoas e de Vince."),
        Movies(name: "O Sexto Sentido", photo: UIImage(named: "sextoSentido"), sumary: "O psicólogo infantil Malcolm Crowe (Bruce Willis) abraça com dedicação o caso de Cole Sear (Haley Joel Osment). O garoto, de 8 anos, tem dificuldades de entrosamento no colégio e vive paralisado de medo. Malcolm, por sua vez, busca se recuperar de um trauma sofrido anos antes, quando um de seus pacientes se suicidou na sua frente."),
        Movies(name: "Tempo de Matar", photo: UIImage(named: "tempoDeMatar"), sumary: "Em Canton, no Mississipi, dois brancos espancam e estupram uma menina negra de dez anos. Eles são presos, mas quando estão sendo levados ao tribunal para terem o valor da sua fiança decretada o pai da garota (Samuel L. Jackson) decide fazer justiça com as próprias mãos e mata os dois na frente de diversas testemunhas, além de acidentalmente ferir seriamente um policial. Ele é preso rapidamente, mas a cidade se torna um barril de pólvora e, além do mais, a defesa tem de se defrontar com um juiz que não permite que no julgamento se mencione a razão que fez o pai cometer o duplo homicídio, pois o julgamento é de assassinato e não de estupro."),
    ]
}
